export const ORDER_PAYMENT = "ORDER_PAYMENT";
export const SAVE_ORDER = "SAVE_ORDER";
export const SAVE_ORDER_SUCCESS = "SAVE_ORDER_SUCCESS";
export const SAVE_ORDER_PROCESS = "SAVE_ORDER_PROCESS";


// row order 

export const SAVE_ROW_ORDER = "SAVE_ROW_ORDER";
export const SAVE_ROW_ORDER_PROCESS = "SAVE_ROW_ORDER_PROCESS";
export const SAVE_ROW_ORDER_SUCCESS = "SAVE_ROW_ORDER_SUCCESS";

export const LIST_ROW_ORDER = "LIST_ROW_ORDER";